forms/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^comment/$', views.comment)
]

forms/models.py
from django.db import models

class Comments(models.Model):
	email = models.EmailField(max_length=50)
	comment = models.CharField(max_length=200)

forms/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comments
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		super(CommentForm, self).__init__(*args, **kwargs)

		self.fields['email'].widget.attrs.update({'class': 'form-control cyan-back'})
		self.fields['comment'].widget.attrs.update({'class': 'form-control cyan-back'})

	def clean_email(self):
		if (self.cleaned_data.get('email', '').endswith('not.ok')):
			raise ValidationError('Invalid email address.')

		return self.cleaned_data.get('email', '')

	def clean(self):
		self.cleaned_data = super(CommentForm, self).clean()
		if ('die' in self.cleaned_data.get('comment', '')):
			raise ValidationError('please enter a good comment.')

		if (self.cleaned_data.get('email', '').endswith('hotmail.com')):
			raise ValidationError('we hate hotmail!')
		
		return self.cleaned_data

forms/settings.py
"""
Django settings for forms project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(bh$07025t=*su0_u&-iy4u5dpb4$rx2#0)07#rg$flhj1j5-$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'forms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'forms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_ROOT, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

forms/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

def index(request):
	all_comments = Comments.objects.all()
	return render(request, 'home.html', {'all_comments': all_comments})

def comment(request):
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/')
	else:
		form = CommentForm()
	return render(request, 'comment.html', {'form': form })

forms/wsgi.py
"""
WSGI config for forms project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "forms.settings")

application = get_wsgi_application()

forms/templates/comment.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

<div class="container">
    <h1> Comment </h1>
    <style>
        .cyan-back {
            background-color: cyan;
        }
        .space {
            margin-top: 5px;
        }
    </style>

    {{ form.errors }}

    <form action="/comment/" method="post" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="id_email">Email:</label>
                {{ form.email }}
            </div>
            <div class="col-md-4">
                <label for="id_comment">Comment:</label>                
                {{ form.comment }}
            </div>
        </div>
        <div class="space">
            <input type="submit" value="Submit" class="btn btn-info"/>
        </div>
    </form>

    <a href="/"> go home </a>
</div>

forms/templates/home.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

<div class="container">
	<h1> Home </h1>

	{% if all_comments %}
		<p> Recent comments: </p>
		<ul>
			{% for comment in all_comments %}
				<li>{{ comment.comment }} <small> - by {{ comment.email }} </small></li>
			{% endfor %}
		</ul>
	{% endif %}

	<a href="/comment"> new comment </a>
</div>